apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-04-12T01:32:34Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: hosting.k8s.local
  name: master-us-west-2c
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  volumeSize: 16
  volumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west-2c
  role: Master
  subnets:
  - us-west-2c
