apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-30T21:02:57Z
  labels:
    kops.k8s.io/cluster: hosting.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  rootVolumeSize: 8
  rootVolumeType: gp2
  rootVolumeIops: 100
  mixedInstancesPolicy:
    instances:
    - t3.micro
    - t2.micro
    onDemandAboveBase: 0
    spotInstancePools: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west-2c
